features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: 'public://125-tem_0.png'
favicon:
  use_default: 0
  path: profiles/contrib/lightning/favicon.ico
  mimetype: image/vnd.microsoft.icon
